name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: //live.webuild.sg
timezone:    Asia/Singapore
encoding:    UTF-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

default_logo : https://assets.webuild.sg/logo-200.jpg
default_day : Sat
default_time : 11am

next_guest: "Subhransu Behera"
next_episode: "037"
next_podcast_start_time: 2016-10-01 11:00 +0800
next_podcast_end_time: 2016-10-01 12:00 +0800
next_profile: /img/037-subhransu-behera-profile.jpg
next_topic: mobile software architecture.
next_connect: 'Connect with Subh on <a href="https://twitter.com/subhransu">Twitter</a> and <a href="https://www.linkedin.com/in/subhransubehera">Linkedin</a>!'
