name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg

next_guest: U-zyn Chua
next_episode: "018"
next_profile: /img/018-uzyn-chua-profile.jpg
next_topic: web security and authentication.
next_connect: Connect with U-zyn on <a href="https://twitter.com/uzyn">twitter</a>, <a href="https://github.com/uzyn">github</a> and <a href="https://github.com/opauth">opauth</a>!
