name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg

next_guest: Winston Teo
next_episode: "017"
next_profile: /img/017-winston-teo-profile.jpg
next_topic: developer happiness and Ruby community events.
next_connect: Connect with Winston on <a href="https://twitter.com/winstonyw">twitter</a>, <a href="https://github.com/winston">github</a> and <a href="http://www.reddotrubyconf.com/">rdrc</a>!
