name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

next_guest: Roland Turner
next_episode: "023"
next_podcast_date: 2014-08-16 11:00 +0800
next_profile: /img/023-roland-turner-profile.jpg
next_topic: community based hardware projects and running <a href="http://www.hackerspace.sg">hackerspaces</a>.
next_connect: Connect with Roland on <a href="https://www.facebook.com/roland.turner">Facebook</a> and <a href="http://raz.cx/">his website</a>!
