name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg

next_guest: Lakshan Parera
next_episode: "014"
next_profile: /img/014-lakshan-parera-profile.jpg
next_topic: startup product development and managing open source projects.
next_connect: Connect with Lakshan on <a href="https://twitter.com/laktek">twitter</a>, <a href="http://github.com/laktek">github</a>!
