name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg
timezone:    Singapore/Singapore
encoding:    UTF-8


next_guest: Kiruthika Curic
next_episode: "020"
next_profile: /img/020-kiruthika-curic-profile.jpg
next_topic: the maker movement and getting involved in <a href="http://makerfairesingapore.com/">Maker Faires</a>
next_connect: Connect with Kiruthika on <a href="https://www.facebook.com/kiruthika.curic">Facebook</a>!
