name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: //live.webuild.sg
timezone:    Asia/Singapore
encoding:    UTF-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

default_logo : https://assets.webuild.sg/logo-100.jpg
default_day : Sat
default_time : 11am

next_guest: "co-hosts"
next_episode: "034"
next_podcast_start_time: 2016-08-13 11:00 +0800
next_podcast_end_time: 2016-08-13 12:00 +0800
next_profile: /img/000-hello-world-profile.jpg
next_topic: the reboot of the live podcast, new audio setup and what's new around the world in engineering and sciences.
next_connect: 'Connect with the co-hosts on <a href="https://twitter.com/webuildsg">Twitter</a>, <a href="https://github.com/webuildsg">Github</a> and <a href="https://www.facebook.com/webuildsg">Facebook</a>!'
