name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: //live.webuild.sg
timezone:    Asia/Singapore
encoding:    UTF-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

default_logo : https://assets.webuild.sg/logo-200.jpg
default_day : Sat
default_time : 11am

next_guest: "Navjot Pawera"
next_episode: "038"
next_podcast_start_time: 2016-10-15 11:00 +0800
next_podcast_end_time: 2016-10-15 12:00 +0800
next_profile: /img/038-navjot-pawera-profile.jpg
next_topic: user experience design for web and mobile.
next_connect: 'Connect with Nav on <a href="https://twitter.com/isnav">Twitter</a>!'
