name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg
timezone:    Asia/Singapore
encoding:    UTF-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

next_guest: "Kiran Jonnalagadda"
next_episode: "027"
next_podcast_start_time: 2014-11-22 11:00 +0800
next_podcast_end_time: 2014-11-22 12:00 +0800
next_profile: /img/027-kiran-jonnalagadda-profile.jpg
next_topic: automating event logistics with python and growing developer communities.
next_connect: 'Connect with Kiran on <a href="https://twitter.com/jackerhack">twitter</a> and <a href="https://hasgeek.com/">hasgeek</a>!'
