name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg
timezone:    Singapore/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

next_guest: Leon Lim
next_episode: "022"
next_podcast_date: 2014-08-02 11:00 +0800
next_profile: /img/022-leon-lim-profile.jpg
next_topic: getting started with hobbyist electronics and spreading digital arts in the community.
next_connect: Connect with Leon on <a href="https://www.facebook.com/gylim78">Facebook</a>!
