name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg
timezone:    Asia/Singapore
encoding:    UTF-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

next_guest: "Alyssa Quek"
next_episode: "031"
next_podcast_start_time: 2015-03-21 11:00 +0800
next_podcast_end_time: 2015-03-21 12:00 +0800
next_profile: /img/031-alyssa-quek-profile.jpg
next_topic: computer vision in python and getting involved in the developer community.
next_connect: 'Connect with Alyssa on <a href="https://twitter.com/alyssaquek">Twitter</a>, <a href="http://scriptogr.am/alyssa">Blog</a> and <a href="https://github.com/alyssaq">Github</a>!'
