name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg

next_guest: Veronica Ng
next_episode: "016"
next_profile: /img/016-veronica-ng-profile.jpg
next_topic: UX and UI for products and open source legal docs for startups.
next_connect: Connect with Veronica on <a href="https://twitter.com/veronism">twitter</a>, <a href="https://github.com/veronism">github</a>!
