name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg
timezone:    Singapore/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am


next_guest: William Hooi
next_episode: "021"
next_profile: /img/021-william-hooi-profile.jpg
next_topic: on <a href="http://makersblock.sg/">maker festivals</a> and community education.
next_connect: Connect with William on <a href="https://www.facebook.com/whooi">Facebook</a>!
