name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://live.webuild.sg
timezone:    Asia/Singapore
encoding:    UTF-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

next_guest: "Honor Hager"
next_episode: "028"
next_podcast_start_time: 2014-12-06 11:00 +0800
next_podcast_end_time: 2014-12-06 12:00 +0800
next_profile: /img/028-honor-hager-profile.jpg
next_topic: Radio Astronomy and connecting people with Arts & Sciences.
next_connect: 'Connect with Honor on <a href="https://twitter.com/honorharger">Twitter</a>, <a href="http://decelerator.blogspot.sg/">Particle Decelerator</a> blog and the <a href="https://www.facebook.com/ArtScienceMuseum">ArtScience Museum</a>!'

