name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

next_guest: "Sebastiaan Deckers"
next_episode: "034"
next_podcast_start_time: 2015-07-18 11:00 +0800
next_podcast_end_time: 2015-07-18 12:00 +0800
next_profile: /img/034-seb-deckers-profile.jpg
next_topic: frontend web technologies and developer productivity.
next_connect: 'Connect with Seb on <a href="https://twitter.com/sebdeckers">Twitter</a>, <a href="https://github.com/cbas">Github</a> and <a href="http://www.cofounders.sg/">CoFounders</a>!'
