name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

next_guest: "Vishnu Prem"
next_episode: "026"
next_podcast_start_time: 2014-11-01 11:00 +0800
next_podcast_end_time: 2014-11-01 12:00 +0800
next_profile: /img/026-vishnu-prem-profile.jpg
next_topic: starting young in tech and getting involved in student groups.
next_connect: 'Connect with Vishnu on <a href="https://twitter.com/burnflare">twitter</a>, on his <a href="http://vishnuprem.com/">website</a> and <a href="http://github.com/burnflare">github</a>!'
