name: We Build SG LIVE
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://localhost:4000
