name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

next_guest: "Eugene Teo"
next_episode: "045"
next_podcast_start_time: 2017-04-22 11:00 +0800
next_podcast_end_time: 2017-04-22 12:00 +0800
next_profile: /img/045-eugene-teo-profile.jpg
next_topic: computer security.
next_connect: 'Connect with Eugene on <a href="https://twitter.com/eugeneteo">Twitter</a>!'
