name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://localhost:4000
timezone:    Singapore/Singapore
encoding:    UTF-8


next_guest: Joshua Koo
next_episode: "019"
next_profile: /img/019-joshua-koo-profile.jpg
next_topic: fun with the web, <a href="http://threejs.org/">threejs</a> and randomness.
next_connect: Connect with Joshua on <a href="https://twitter.com/blurspline">twitter</a>, <a href="https://github.com/zz85">github</a>!
