name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

next_guest: "Michelle Lye"
next_episode: "032"
next_podcast_start_time: 2015-04-04 11:00 +0800
next_podcast_end_time: 2015-04-04 12:00 +0800
next_profile: /img/032-michelle-lye-profile.jpg
next_topic: playing with microcontrollers and teaching electronics.
next_connect: 'Connect with Michelle on <a href="https://twitter.com/monolye">Twitter</a>, <a href="http://mopusworks.com/">Mopus Words</a> and <a href="http://mopusworks.com/product-category/tweeq-core/">Tweeq</a>!'
