name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

next_guest: "Adnan Jalaludin"
next_episode: "047"
next_podcast_start_time: 2017-06-10 11:00 +0800
next_podcast_end_time: 2017-06-10 12:00 +0800
next_profile: /img/046-lim-chee-aun-profile.jpg
next_topic: DFM (design for manufacturability) for electronics.
next_connect: 'Connect with Adnan on <a href="https://github.com/catmaker">GitHub</a>!'
