name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

next_guest: "Hakim Hamid"
next_episode: "041"
next_podcast_start_time: 2017-01-07 11:00 +0800
next_podcast_end_time: 2017-01-07 12:00 +0800
next_profile: /img/041-hakim-hamid-profile.jpg
next_topic: mechanical engineeering.
next_connect: 'Connect with Hakim Hamid on <a href="https://www.facebook.com/hakim.hamid">Facebook</a> and <a href="https://www.linkedin.com/in/abdul-hakim-hamid-36027414">LinkedIn</a>!'
