name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"


next_guest: Arul Kumaran
next_episode: "024"
next_podcast_date: 2014-09-14 13:00 +0800
next_profile: /img/024-arul-kumaran-profile.jpg
next_topic: <a href="https://www.luracast.com/products/restler">creating web APIs </a> and types of APIs.
next_connect: Connect with Arul on <a href="https://www.facebook.com/r.arulkumaran">Facebook</a> and <a href="https://www.luracast.com/products">his website</a>!
