name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://localhost:4000

next_guest: Martin Brochhaus
next_episode: "015"
next_profile: /img/015-martin-brochhaus-profile.jpg
next_topic: developing with Python and organising talks in a tech conference.
next_connect: Connect with Martin on <a href="https://twitter.com/mbrochh">twitter</a>, <a href="https://plus.google.com/+MartinBrochhaus">google+</a>, <a href="https://github.com/mbrochh">github</a>!
