name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: redcarpet
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"


next_guest: "Anna, Roland, Mic"
next_episode: "025"
next_podcast_date: 2014-10-4 11:00 +0800
next_profile: /img/025-anna-mic-roland-profile.jpg
next_topic: open source hardware and software.
next_connect: 'Connect with Anna on <a href="mailto:annaf@nus.edu.sg">email</a>, with Roland on his <a href="http://www.rolandturner.com">website</a> and Mic on <a href="http://www.twitter.com/coderkungfu">twitter</a> and his <a href="http://coderkungfu.com/">website</a> !'
